language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
sudo: false
notifications:
  irc: irc.freenode.org#socket.io
matrix:
  include:
  - node_js: '0.10'
    env: BROWSER_NAME=chrome BROWSER_VERSION=latest
  - node_js: '0.10'
    env: BROWSER_NAME=safari BROWSER_VERSION=latest
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=6
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=7
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=8
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=9
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=10 BROWSER_PLATFORM="Windows 2012"
  - node_js: '0.10'
    env: BROWSER_NAME=ie BROWSER_VERSION=latest BROWSER_PLATFORM="Windows 2012"
# zuul doesn't work on Microsoft Edge: issues/232
# - node_js: '0.10'
#   env: BROWSER_NAME=microsoftedge BROWSER_VERSION=latest BROWSER_PLATFORM="Windows 10"
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=6.1
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=7.1
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=8.4
  - node_js: '0.10'
    env: BROWSER_NAME=iphone BROWSER_VERSION=latest
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.0
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.1
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.2
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=4.3
# It seems Date doesn't work properly on Android 4.4
# - node_js: '0.10'
#   env: BROWSER_NAME=android BROWSER_VERSION=4.4
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=5.0
  - node_js: '0.10'
    env: BROWSER_NAME=android BROWSER_VERSION=latest
